In [129]:
import numpy as np

In [130]:
na = np.arange(27)
na

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [131]:
na.reshape(3,3,3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [132]:
m = np.asarray([[123, 12, 123, 12, 33], [], []], dtype=object)
type(m)

numpy.ndarray

In [133]:
import cv2

In [134]:
img = cv2.imread("smallgray.png", 0)
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [135]:
cv2.imwrite("newsmallgray.png",img)

True

In [136]:
img[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [137]:
img[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [138]:
img.shape

(3, 5)

In [139]:
for i in img:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [140]:
for i in img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [141]:
img_hstack = np.hstack((img, img))
img_hstack

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [142]:
img_vstack = np.vstack((img, img))
img_vstack

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

Splitting Array

In [143]:
img_hsplit = np.hsplit(img_vstack,5)
img_hsplit


[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [144]:
img_vsplit = np.vsplit(img_vstack, 3)
img_vsplit


[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]